micronaut:
  server:
    port: 8090
  application:
    name: booking
vertx:
  pg:
    client:
      maxSize: 5
      uri: postgresql://booking:booking@localhost:5432/booking
jackson:
  serialization:
    writeDatesAsTimestamps: false

flyway:
  datasources:
    default:
      url: 'jdbc:postgresql://localhost:5432/booking'
      username: 'booking'
      password: 'booking'
      driverClassName: 'org.postgresql.Driver'
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9092


endpoints:
  flyway:
    enabled: true
    sensitive: false